# EasyAdmin配置示例
# 将此配置添加到你的主应用的 config/packages/easy_admin.yaml 中

easy_admin:
    design:
        menu:
            - label: '阿里云VOD管理'
              icon: 'fa fa-video'
              children:
                - label: '配置管理'
                  entity: 'Tourze\AliyunVodBundle\Entity\AliyunVodConfig'
                  icon: 'fa fa-cog'
                - label: '视频管理'
                  entity: 'Tourze\AliyunVodBundle\Entity\Video'
                  icon: 'fa fa-film'
                - label: '转码任务'
                  entity: 'Tourze\AliyunVodBundle\Entity\TranscodeTask'
                  icon: 'fa fa-tasks'
                - label: '播放记录'
                  entity: 'Tourze\AliyunVodBundle\Entity\PlayRecord'
                  icon: 'fa fa-list'
                - label: '视频上传'
                  url: '/admin/video-upload'
                  icon: 'fa fa-upload'
                - label: '播放统计'
                  url: '/admin/statistics'
                  icon: 'fa fa-chart-bar'

    entities:
        # 阿里云VOD配置
        Tourze\AliyunVodBundle\Entity\AliyunVodConfig:
            class: Tourze\AliyunVodBundle\Controller\Admin\AliyunVodConfigCrud
            
        # 视频管理
        Tourze\AliyunVodBundle\Entity\Video:
            class: Tourze\AliyunVodBundle\Controller\Admin\VideoCrud
            
        # 转码任务
        Tourze\AliyunVodBundle\Entity\TranscodeTask:
            class: Tourze\AliyunVodBundle\Controller\Admin\TranscodeTaskCrud
            
        # 播放记录
        Tourze\AliyunVodBundle\Entity\PlayRecord:
            class: Tourze\AliyunVodBundle\Controller\Admin\PlayRecordCrud 